spring:
  application:
    name: dividends

  output:
    ansi:
      enabled: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    show-sql: true